# Generated by Django 5.2.3 on 2025-06-20 09:27

import apply.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dagree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Nomi')),
                ('status', models.BooleanField(default=False, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Daraja',
                'verbose_name_plural': 'Darajalar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Familya')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Sharif')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqamini '+998901234567' formatida kiriting.", regex='^\\+?998\\s?\\d{2}\\s?\\d{3}\\s?\\d{2}\\s?\\d{2}$')], verbose_name='Telefon raqami')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram username yoki telefon nomer')),
                ('passport', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Pasport seriyasini 'AA1234567' formatida kiriting.", regex='^[A-Z]{2}\\d{7}$')], verbose_name='Pasport seriyasi va raqami')),
                ('address_of_permanent_residence', models.CharField(max_length=500, verbose_name='Doimiy yashash manzili')),
                ('photo', models.ImageField(upload_to=apply.models.FileUploadPath('photos'), verbose_name='Surat (3x4)')),
                ('passport_copy', models.FileField(upload_to=apply.models.FileUploadPath('passports'), verbose_name='Pasport nusxasi')),
                ('diploma', models.FileField(upload_to=apply.models.FileUploadPath('diplomas'), verbose_name='Diplom/Shaxodatnoma (ilovasi bilan)')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to=apply.models.FileUploadPath('additional'), verbose_name="Qo'shimcha hujjatlar")),
                ('dtm_file', models.FileField(blank=True, null=True, upload_to=apply.models.FileUploadPath('dtm_files'), verbose_name="DTM qaydnomasi (mavjud bo'lsa)")),
                ('dtm_ball', models.FloatField(blank=True, null=True, verbose_name="DTM bali (mavjud bo'lsa)")),
                ('language', models.CharField(choices=[('uzbek', 'O`zbek tili'), ('russian', 'Rus tili')], max_length=10, verbose_name="Ta'lim tili")),
                ('bilateral_contract', models.FileField(upload_to=apply.models.FileUploadPath('contracts'), verbose_name='Ikki tomonlama shartnoma')),
                ('tripartite_contract', models.FileField(upload_to=apply.models.FileUploadPath('contracts'), verbose_name="Uch tomonlama shartnoma (to'lov-kontrakt)")),
                ('status', models.BooleanField(default=False, verbose_name='Holati (tasdiqlangan/tasdiqlanmagan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apply.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sciences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Nomi')),
                ('status', models.BooleanField(default=False, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol matni')),
                ('A', models.TextField(verbose_name='A variant')),
                ('B', models.TextField(verbose_name='B variant')),
                ('C', models.TextField(verbose_name='C variant')),
                ('D', models.TextField(verbose_name='D variant')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('sciences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apply.sciences', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='DirectionOfEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Nomi')),
                ('status', models.BooleanField(default=False, verbose_name='Holati')),
                ('externally', models.BooleanField(default=False)),
                ('personally', models.BooleanField(default=False)),
                ('remote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('dagree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apply.dagree', verbose_name='Daraja')),
                ('science_is_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_directions', to='apply.sciences', verbose_name='Birinchi asosiy fan')),
                ('science_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_directions', to='apply.sciences', verbose_name='Ikkinchi asosiy fan')),
            ],
            options={
                'verbose_name': "Ta'lim yo'nalishi",
                'verbose_name_plural': "Ta'lim yo'nalishlari",
            },
        ),
    ]
