# Generated by Django 5.2.3 on 2025-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dagree',
            name='name_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='dagree',
            name='name_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='dagree',
            name='name_uz',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='directionofeducation',
            name='name_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='directionofeducation',
            name='name_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='directionofeducation',
            name='name_uz',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='question',
            name='A_en',
            field=models.TextField(null=True, verbose_name='A variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='A_ru',
            field=models.TextField(null=True, verbose_name='A variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='A_uz',
            field=models.TextField(null=True, verbose_name='A variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='B_en',
            field=models.TextField(null=True, verbose_name='B variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='B_ru',
            field=models.TextField(null=True, verbose_name='B variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='B_uz',
            field=models.TextField(null=True, verbose_name='B variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='C_en',
            field=models.TextField(null=True, verbose_name='C variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='C_ru',
            field=models.TextField(null=True, verbose_name='C variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='C_uz',
            field=models.TextField(null=True, verbose_name='C variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='D_en',
            field=models.TextField(null=True, verbose_name='D variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='D_ru',
            field=models.TextField(null=True, verbose_name='D variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='D_uz',
            field=models.TextField(null=True, verbose_name='D variant'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.TextField(null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_ru',
            field=models.TextField(null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_uz',
            field=models.TextField(null=True, verbose_name='Savol matni'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='sciences',
            name='name_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='sciences',
            name='name_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='sciences',
            name='name_uz',
            field=models.CharField(max_length=1000, null=True, verbose_name='Nomi'),
        ),
    ]
