# Generated by Django 5.2.3 on 2025-06-24 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_dagree_name_en_dagree_name_ru_dagree_name_uz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dagree',
            name='author',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='author',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='dagree',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apply.dagree', verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='externally',
            field=models.BooleanField(default=False, verbose_name='Sirtqi'),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='personally',
            field=models.BooleanField(default=False, verbose_name='Kunduzgi'),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='Masofaviy'),
        ),
        migrations.AlterField(
            model_name='region',
            name='author',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.AlterField(
            model_name='sciences',
            name='author',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
