# Generated by Django 5.2.3 on 2025-06-24 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_alter_dagree_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol matni')),
                ('A', models.TextField(verbose_name='A variant')),
                ('B', models.TextField(verbose_name='B variant')),
                ('C', models.TextField(verbose_name='C variant')),
                ('D', models.TextField(verbose_name='D variant')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('language', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], max_length=10, verbose_name='Test tili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('sciences', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apply.sciences', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
    ]
