# Generated by Django 5.2.3 on 2025-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Holati'),
        ),
    ]
