# Generated by Django 5.2.3 on 2025-06-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_question_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionofeducation',
            name='externally',
            field=models.BooleanField(default=False, verbose_name="Sirtqi ta'lim"),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='personally',
            field=models.BooleanField(default=False, verbose_name="Kunduzgi ta'lim"),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='remote',
            field=models.BooleanField(default=False, verbose_name="Masofaviy ta'lim"),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Holati'),
        ),
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
    ]
