# Generated by Django 5.2.3 on 2025-06-25 06:55

import apply.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_alter_directionofeducation_externally_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=100, verbose_name='Ariza raqami')),
                ('form_od_education', models.CharField(choices=[('externally', "Sirtqi ta'lim"), ('personally', "Kunduzgi ta'lim"), ('remote', "Masofaviy ta'lim")], max_length=10, verbose_name='Jinsi')),
                ('surname', models.CharField(max_length=100, verbose_name='Familya')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Sharif')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqamini '+998901234567' formatida kiriting.", regex='^\\+?998\\s?\\d{2}\\s?\\d{3}\\s?\\d{2}\\s?\\d{2}$')], verbose_name='Telefon raqami')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram username yoki telefon nomer')),
                ('passport', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message="Pasport seriyasini 'AA1234567' formatida kiriting.", regex='^[A-Z]{2}\\d{7}$')], verbose_name='Pasport seriyasi va raqami')),
                ('jshir', models.IntegerField(blank=True, max_length=14, unique=True, verbose_name='JSHIR')),
                ('address_of_permanent_residence', models.CharField(max_length=500, verbose_name='Doimiy yashash manzili')),
                ('photo', models.ImageField(upload_to=apply.models.FileUploadPath('photos'), verbose_name='Surat (3x4)')),
                ('passport_copy', models.FileField(upload_to=apply.models.FileUploadPath('passports'), verbose_name='Pasport nusxasi')),
                ('diploma', models.FileField(upload_to=apply.models.FileUploadPath('diplomas'), verbose_name='Diplom/Shaxodatnoma (ilovasi bilan)')),
                ('additional_documents', models.FileField(blank=True, null=True, upload_to=apply.models.FileUploadPath('additional'), verbose_name="Qo'shimcha hujjatlar")),
                ('dtm_file', models.FileField(blank=True, null=True, upload_to=apply.models.FileUploadPath('dtm_files'), verbose_name="DTM qaydnomasi (mavjud bo'lsa)")),
                ('dtm_ball', models.FloatField(blank=True, null=True, verbose_name="DTM bali (mavjud bo'lsa)")),
                ('language', models.CharField(choices=[('uzbek', "O'zbek tili"), ('russian', 'Rus tili')], max_length=10, verbose_name="Ta'lim tili")),
                ('bilateral_contract', models.FileField(upload_to=apply.models.FileUploadPath('contracts'), verbose_name='Ikki tomonlama shartnoma')),
                ('tripartite_contract', models.FileField(upload_to=apply.models.FileUploadPath('contracts'), verbose_name="Uch tomonlama shartnoma (to'lov-kontrakt)")),
                ('status', models.BooleanField(default=False, verbose_name='Holati (tasdiqlangan/tasdiqlanmagan)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dagree', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apply.dagree', verbose_name='Daraja')),
                ('direction_of_education', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apply.directionofeducation', verbose_name='Daraja')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apply.region', verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
