# Generated by Django 5.2.3 on 2025-06-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0009_applicationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
    ]
