# Generated by Django 5.2.3 on 2025-06-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0011_applicationform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationform',
            old_name='form_od_education',
            new_name='form_of_education',
        ),
    ]
