# Generated by Django 5.2.3 on 2025-06-25 09:51

import apply.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0012_rename_form_od_education_applicationform_form_of_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='bilateral_contract',
            field=models.FileField(blank=True, upload_to=apply.models.FileUploadPath('contracts'), verbose_name='Ikki tomonlama shartnoma'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='direction_of_education',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apply.directionofeducation', verbose_name="Talim yo'nalishi"),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='jshir',
            field=models.CharField(max_length=14, unique=True, verbose_name='JSHIR'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('pending', 'Yangi'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20, verbose_name='Ariza holati'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='tripartite_contract',
            field=models.FileField(blank=True, upload_to=apply.models.FileUploadPath('contracts'), verbose_name="Uch tomonlama shartnoma (to'lov-kontrakt)"),
        ),
    ]
