# Generated by Django 5.2.3 on 2025-06-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0013_alter_applicationform_bilateral_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='additional_documents_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='dtm_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='test_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='form_of_education',
            field=models.CharField(choices=[('externally', 'External learning'), ('personally', 'Full-time'), ('remote', 'Distance learning')], max_length=10, verbose_name="Ta'lim shakli"),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Jinsi'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='language',
            field=models.CharField(choices=[('uzbek', 'Uzbek'), ('russian', 'Russian')], max_length=10, verbose_name="Ta'lim tili"),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(choices=[('pending', 'New'), ('review', 'Under review'), ('approved', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Ariza holati'),
        ),
    ]
