# Generated by Django 5.2.3 on 2025-06-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0014_applicationform_additional_documents_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='science_is_one',
            field=models.BooleanField(default=False, verbose_name='Birinchi fan'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='science_two',
            field=models.BooleanField(default=False, verbose_name='Ikkinchi fan'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='additional_documents_status',
            field=models.BooleanField(default=False, verbose_name="Qo'shimcha hujjatlar holati"),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='dtm_status',
            field=models.BooleanField(default=False, verbose_name='DTM qaydnomasi holati'),
        ),
    ]
