# Generated by Django 5.2.3 on 2025-06-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0015_applicationform_science_is_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='test_status',
            field=models.BooleanField(default=True),
        ),
    ]
