# Generated by Django 5.2.3 on 2025-06-24 10:25

import application.models
import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(default='', upload_to='img/about')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Haqida',
                'verbose_name_plural': 'Haqida',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nomi')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/admission')),
                ('order_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Qabul',
                'verbose_name_plural': 'Qabul',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='img/banner')),
            ],
            options={
                'verbose_name': 'Banner rasm',
                'verbose_name_plural': 'Banner rasm',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('img', models.ImageField(default='', upload_to='img/departament')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Kafedra',
                'verbose_name_plural': 'Kafedra',
            },
        ),
        migrations.CreateModel(
            name='Esg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nomi')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/GrantsAndScholarships')),
                ('order_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Brm',
                'verbose_name_plural': 'Brm',
            },
        ),
        migrations.CreateModel(
            name='Fotogalareya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nomi')),
                ('img', models.ImageField(default='', upload_to='img/fotogalareya')),
            ],
            options={
                'verbose_name': 'Fotogalareya',
                'verbose_name_plural': 'Fotogalareya',
            },
        ),
        migrations.CreateModel(
            name='GrantsAndScholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nomi')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/GrantsAndScholarships')),
                ('order_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Grantlar va Stipendiyalar',
                'verbose_name_plural': 'Grantlar va Stipendiyalar',
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='FIO')),
                ('phone', models.CharField(default='', max_length=1000, verbose_name='Telefon')),
                ('mail', models.CharField(default='', max_length=1000, verbose_name='Email')),
                ('job_title', models.CharField(default='', max_length=1000, verbose_name='Lavozimi')),
                ('img', models.ImageField(default='', upload_to='img/managment')),
                ('short_info', models.CharField(default='', max_length=1000, verbose_name='Qizqa izoh')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Boshqaruv',
                'verbose_name_plural': 'Boshqaruv',
            },
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Yangilik turi',
                'verbose_name_plural': 'Yangilik turi',
            },
        ),
        migrations.CreateModel(
            name='OurPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nomi')),
                ('link', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Link')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/partners')),
            ],
            options={
                'verbose_name': 'Xamkorlar',
                'verbose_name_plural': 'Xamkorlar',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nomi')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/programs')),
            ],
            options={
                'verbose_name': 'Dasturlar',
                'verbose_name_plural': 'Dasturlar',
            },
        ),
        migrations.CreateModel(
            name='StudentCouncil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nomi')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/admission')),
            ],
            options={
                'verbose_name': 'Talabalar kengashi',
                'verbose_name_plural': 'Talabalar kengashi',
            },
        ),
        migrations.CreateModel(
            name='VisionAndMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(default='', upload_to='img/mission')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Maqsad va vazifalar',
                'verbose_name_plural': 'Maqsad va vazifalar',
            },
        ),
        migrations.CreateModel(
            name='DepartmentTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='FIO')),
                ('phone', models.CharField(default='', max_length=1000, verbose_name='Telefon')),
                ('mail', models.CharField(default='', max_length=1000, verbose_name='Email')),
                ('job_title', models.CharField(default='', max_length=1000, verbose_name='Lavozimi')),
                ('img', models.ImageField(default='', upload_to='img/teachers')),
                ('short_info', models.CharField(default='', max_length=1000, verbose_name='Qizqa izoh')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.department', verbose_name='Turi')),
            ],
            options={
                'verbose_name': "Kafedra o'qituvchilari",
                'verbose_name_plural': "Kafedra o'qituvchilari",
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='Nomi')),
                ('short_info', models.CharField(default='', max_length=1000, verbose_name='Qisqa iozh')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img_news', models.ImageField(default='', upload_to='img/news')),
                ('views', models.IntegerField(default='0', verbose_name="Ko'rishlar soni")),
                ('status', models.BooleanField(default=False, verbose_name='Slayderni yoqish')),
                ('tg_status', models.BooleanField(default=False, verbose_name='Telegramga chiqarish')),
                ('telegram_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.newstype', verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangilik',
            },
        ),
        migrations.CreateModel(
            name='NewsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to=application.models.news_img_upload_path)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='application.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik rasm',
                'verbose_name_plural': 'Yangilik rasm',
            },
        ),
        migrations.CreateModel(
            name='ProgramDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Nomi')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/programs/direction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.programs', verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Dasturlar',
                'verbose_name_plural': 'Dasturlar',
            },
        ),
    ]
